spring:
  application:
    name: vote-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    user:
      name: minguni
      password: minguni
  datasource:
    url: jdbc:mariadb://localhost:3307/vote-db
    username: minguni
    password: minguni
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionInitSql: "SET time_zone='Asia/Seoul'"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul  # 드라이버 ↔ DB 변환 기준을 KST로
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vote-room-local-consumer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: Asia/Seoul        # JSON 입·출력 전부 한국시간으로
springdoc:
  swagger-ui:
    path: /api

server:
  port: 8082
  shutdown: graceful
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:127.0.0.1}

vottega:
  security:
    filter-paths: [ "/api/vote/**" ]