spring:
  security:
    user:
      name: minguni
      password: minguni
  datasource:
    url: jdbc:mariadb://localhost:3307/vote-db
    username: minguni
    password: minguni
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: room-local-consumer
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      auto.register.schemas: true
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: /api
room:
  service:
    url: http://localhost:8080

server:
  port: 8082